version: "3.7"

services:
  bank-management-container:
    image: bank-management:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - C:/data/bank-management
    ports:
      - "8080:8080"